import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next-js Pratcis',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='max-w-4xl mx-auto py-10'>{children}</body>
    </html>
  )
}
