import Navbar from '@/components/Navbar'
import './css/globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next-js Pratcis',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='font-serif'>
      <body className='max-w-5xl mx-auto '>
        <header>
          <Navbar/>
        </header>
        <main className='py-10 px-4'>
          {children}
        </main>  
      </body>
    </html>
  )
}
